spring.application.name=desafio3-reservas-eventos
server.port=8080

# Conexion a MySQL
# Primero crea la base de datos con el script sistema_reservas_db.sql
spring.datasource.url=jdbc:mysql://localhost:3306/reservas_eventos_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Inicializacion del script SQL
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/sistema_reservas_db.sql

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Fix Swagger / Spring Boot
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000


